### ISSUE TITLE
Could you provide the pre-trained weights on the CelebA dataset?

### ISSUE THREAD

**Issue by JohnCarpenter2** [sinahmr/parted-vae#1] opened 2024-03-01 03:07 UTC
Thanks a lot.

**Comment by sinahmr** [comment] 2024-03-01 20:23
Hi,
I could find a file, but I'm not sure if it works and if it is the final one.
You can download it from [here](https://drive.google.com/file/d/1O-PLn8c_TzX9Xnuq8Ig1lanisWcMjFCJ/view?usp=sharing).
Hope it helps.

**Comment by JohnCarpenter2** [comment] 2024-03-02 06:28
Thank you for providing the pre-trained weights. Could you please provide the corresponding JSON file for loading the pre-trained weights? We have discovered that the code requires a JSON file to load the model.

**Comment by sinahmr** [comment] 2024-03-02 15:07
Oh, sorry. I saw that file the other day but didn't remember it was necessary. It has been a long time.
I edited the link in the previous answer, please redownload it.

**Comment by JohnCarpenter2** [comment] 2024-03-03 08:26
Thank you for providing the JSON file. We executed the evaluation code of Parted-VAE on the CelebA dataset. However, the following error occurred:
```
Traceback (most recent call last):
  File "main.py", line 113, in <module>
    model = load(load_model_path, img_size=img_size, disc_priors=disc_priors, device=device)
  File "/data/parted-vae/parted-vae/utils/load_model.py", line 16, in load
    model = VAE(img_size=img_size, latent_spec=latent_spec, c_priors=disc_priors, device=device)
  File "/data/parted-vae/parted-vae/partedvae/models.py", line 193, in __init__
    self.u_prior_means = nn.Parameter(torch.randn(self.sum_c_dims, self.single_u_dim), requires_grad=True)
  File "/miniconda3/envs/face_ax/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'VAE' object has no attribute 'single_u_dim
```
We checked the JSON file and found that the "single_u" parameter is missing. 
Could you please provide the JSON file with the "single_u" parameter?

Thanks!

**Comment by sinahmr** [comment] 2024-03-03 22:39
I think you can just set it to 1.

**Comment by JohnCarpenter2** [comment] 2024-03-04 07:07
> I think you can just set it to 1.

Thanks for your respond. We followed your instruction. However, we got the following error:
```
Traceback (most recent call last):
  File "main.py", line 113, in <module>
    model = load(load_model_path, img_size=img_size, disc_priors=disc_priors, device=device)
  File "/data/parted-vae/parted-vae/utils/load_model.py", line 16, in load
    model = VAE(img_size=img_size, latent_spec=latent_spec, c_priors=disc_priors, device=device)
  File "/data/parted-vae/parted-vae/partedvae/models.py", line 200, in __init__
    self.logsoftmaxer = PartialLogSoftmax(self.c_dims, device=self.device)
  File "/data/parted-vae/parted-vae/partedvae/models.py", line 17, in __init__
    self.sum_dims = sum(dimensions)
TypeError: 'int' object is not iterable
```

**Comment by sinahmr** [comment] 2024-03-05 08:08
Does the json file correctly set `c_dims` to `[4, 3, 2, 3, 2, 2, 2, 2]`?
I currently cannot try the json file and reproduce the errors, I can do it in a week if that works.

**Comment by JohnCarpenter2** [comment] 2024-03-06 01:03
> Does the json file correctly set `c_dims` to `[4, 3, 2, 3, 2, 2, 2, 2]`? I currently cannot try the json file and reproduce the errors, I can do it in a week if that works.

No, the content of the JSON file is:
``` json
{
        "lr_warm_up": 0.000508,
        "lr_model": 0.000511,
        "z_capacity": [0.0, 28.56, 120000, 1076.0],
        "dz_1_capacity": [0.0, 10.68, 120000, 900.0],
        "dz_2_capacity": [0.0, 0, 120000, 900.0],
        "g_z": 1076.000000,
        "g_c": 2036.000000,
        "g_dz": 900.000000,
        "g_h": 10.040000,
        "g_bc_1": 546.000000,
        "g_bc_2": 0.000000,
        "bc_threshold_1": 0.187200,
        "bc_threshold_2": 0.000000,
        "recon_type": "abs",
        "latent_spec": {"cont": 10, "disc": [4, 3, 2, 3, 2, 2, 2, 2], "c1_until": 8, "single_c1_embedding_dim": 1, "single_c2_embedding_dim": 0},
        "epochs": 100,
        "dataset": "celeba"
        }
```

**Comment by sinahmr** [comment] 2024-03-08 17:21
I spent some time in the code and found out that we have forgotten to align our models and specs after cleaning and refactoring the code. I tried my best to make the correct alignment and committed the changes. I don't have access to the datasets so I had to set `LOAD_DATASET = False`, but the model seems to be loaded correctly now.
Sorry for the inconvenience, it's quite an old project and I don't remember many details.

**Comment by JohnCarpenter2** [comment] 2024-03-11 03:22
Thank you for dedicating your time. We have conducted the evaluation process on the CelebA datasets, and the results are presented below. Do these results indicate that we have successfully reproduced PartedVAE?
![recon](https://github.com/sinahmr/parted-vae/assets/133960045/04cfcd7c-5a08-49de-b489-30fbbecf7b8f)

**Comment by sinahmr** [comment] 2024-03-11 17:15
It seems like that. No worries, thanks for your interest.

**Closed as completed by sinahmr** 2024-03-11 17:15 UTC
